In [2]:
import numpy as np
import pandas as pd

def calc_Rs(R1, R2, A):
    midR = (R1+R2)/2
    Ro = (A/np.pi+4*midR**2)/4/midR
    Ri = 2*midR - Ro   
    return Ri, midR, Ro

# Model 1

In [3]:
# Rings radius
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6

AIRR = 19*AF
AFR1 = 18*AF
AFR2 = 24*AF
AFR3 = 24*AF

R = []

Ai = AIRR
IRR = np.sqrt(1/np.pi*Ai)
R.append(IRR)
print('IRR: ', np.round(IRR, 2))

Ai += AFR1
FR1 = np.sqrt(1/np.pi*Ai)
R.append(FR1)
print('FR1: ', np.round(FR1, 2))

Ai += AFR2
FR2 = np.sqrt(1/np.pi*Ai)
R.append(FR2)
print('FR2: ', np.round(FR2, 2))

Ai += AFR3
FR3 = np.sqrt(1/np.pi*Ai)
R.append(FR3)
print('FR3: ', np.round(FR3, 2))

ORR3 = 297.3
R.append(ORR3)

R = np.array(R)

IRR:  82.39
FR1:  114.97
FR2:  147.62
FR3:  174.26


In [4]:
Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac

print('R1:')
n = int(np.floor((FR1-IRR)/1.88))
p = (FR1-IRR)/n
R1 = [IRR]
for i in range(n-1):
    R1.append(R1[-1]+p)
print(np.round(R1, 2))
R1 = np.array(R1)
Rt = sum(R1)
t = (-2*Rt + np.sqrt(4*Rt**2+4*n*AcR1/np.pi))/2/n
print(t)
R1o = R1 + t
# print(np.round(Ro, 2))
# print(sum(np.pi*(Ro**2-R**2)))

print('R2:')
n = int(np.floor((FR2-FR1)/1.88))
# print(n)
p = (FR2-FR1)/n
# print(p)
R2 = [FR1]
for i in range(n-1):
    R2.append(R2[-1]+p)
print(np.round(R2, 2))
R2 = np.array(R2)
Rt = sum(R2)
t = (-2*Rt + np.sqrt(4*Rt**2+4*n*AcR2/np.pi))/2/n
print(t)
R2o = R2 + t
# print(np.round(Ro, 2))
# print(sum(np.pi*(Ro**2-R**2)))

print('R3:')
n = int(np.floor((FR3-FR2)/1.88))
# print(n)
p = (FR3-FR2)/n
# print(p)
R3 = [FR2]
for i in range(n-1):
    R3.append(R3[-1]+p)
print(np.round(R3, 2))
R3 = np.array(R3)
Rt = sum(R3)
t = (-2*Rt + np.sqrt(4*Rt**2+4*n*AcR3/np.pi))/2/n
print(t)
R3o = R3 + t
# print(np.round(Ro, 2))
# print(sum(np.pi*(Ro**2-R**2)))


R1:
[ 82.39  84.31  86.22  88.14  90.06  91.97  93.89  95.81  97.72  99.64
 101.56 103.47 105.39 107.31 109.22 111.14 113.06]
0.4220423255431155
R2:
[114.97 116.89 118.81 120.73 122.66 124.58 126.5  128.42 130.34 132.26
 134.18 136.1  138.02 139.94 141.86 143.78 145.7 ]
0.4221356006152532
R3:
[147.62 149.53 151.43 153.33 155.24 157.14 159.04 160.94 162.85 164.75
 166.65 168.55 170.46 172.36]
0.4177174096544474


In [5]:
# power density averaged in the ring (divided into layers)
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6
AFR1 = 18*AF
AFR2 = 24*AF
AFR3 = 24*AF

Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac


file = pd.read_csv('power.csv')

# W/cm3
R1Fs = np.zeros(10)
for i in range(1, 7):
    fi = np.array(file['F'+str(i)].tolist())
    R1Fs += fi/6/1e6

R2Fs = np.zeros(10)
for i in range(7, 15):
    fi = np.array(file['F'+str(i)].tolist())
    R2Fs += fi/8/1e6

R3Fs = np.zeros(10)
for i in range(15, 23):
    fi = np.array(file['F'+str(i)].tolist())
    R3Fs += fi/8/1e6

QR1s = R1Fs*AFR1/(AFR1-AcR1)
QR2s = R2Fs*AFR2/(AFR2-AcR2)
QR3s = R3Fs*AFR3/(AFR3-AcR3)
print('Ring one power density: ', QR1s)
print('Ring two power density: ', QR2s)
print('Ring three power density: ', QR3s)

Ring one power density:  [ 4.9573133   5.68414705  6.43529391  7.22205732  8.24619338  9.83422275
 11.11919146 12.03093274 11.61355785  8.95553876]
Ring two power density:  [3.88017895 4.55342791 5.33080732 5.97094567 6.74256671 8.11513723
 9.00992332 9.59055856 8.97985186 6.61380325]
Ring three power density:  [ 4.21320445  4.99842164  5.82826616  6.5459825   7.44364777  9.06654726
 10.14528115 10.83100657 10.10481264  7.13125642]


In [6]:
# simple - film
rho = 5.7030  # [kg/m3] 6.4 MPa 259 C
cp = 5.188  # [J/g/K] 6.4 MPa 259 C [2]
cp *= 1e3  # [J/kg/K]
mu = 2.9744e-5  # Pa.s 6.4 MPa 259 C
v = 1701.71  # cm/s
v /= 100  # m/s

Ri = np.concatenate([R1, R2, R3])
Ro = np.concatenate([R1o, R2o, R3o])

ri = Ri/100 # m
ro = Ro/100
Ah = np.pi*(ro**2-ri**2)
Ph = 2*np.pi*(ri+ro)
Dh = 4*Ah/Ph
Re = rho * v * Dh / mu
# print('Re: ', Re)

k = 0.41 # W/m/K
Pr = mu * cp/k
# print('Pr: ', Pr)

Nu = 0.023*(Re**0.8)*(Pr**0.4)
# print('Nu: ', Nu)
h = Nu/Dh * k  # W/m^2/K
# print('h: ', h)

h /= 1e4  # W/cm^2/K

ri *= 100  # cm
ro *= 100  # cm
dr = 0.01  # cm

kgci = h * (ri + dr) * np.log(1 + dr/ri)
kgco = h * (ro + dr) * np.log(1 + dr/ro)
print('ki: ', np.average(kgci))  # W/cm/C
print('ko: ', np.average(kgco))  # W/cm/C

ki:  0.0026954079929609504
ko:  0.0026954075925975027


# Model 2

In [7]:
# Rings radius
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6

AIRR = 19*AF
AFR1 = 18*AF
AFR2 = 24*AF
AFR3 = 24*AF

R = []

Ai = AIRR
IRR = np.sqrt(1/np.pi*Ai)
R.append(IRR)
print('IRR: ', np.round(IRR, 2))

Ai += AFR1
FR1 = np.sqrt(1/np.pi*Ai)
R.append(FR1)
print('FR1: ', np.round(FR1, 2))

Ai += AFR2
FR2 = np.sqrt(1/np.pi*Ai)
R.append(FR2)
print('FR2: ', np.round(FR2, 2))

Ai += AFR3
FR3 = np.sqrt(1/np.pi*Ai)
R.append(FR3)
print('FR3: ', np.round(FR3, 2))

ORR3 = 297.3
R.append(ORR3)

R = np.array(R)

IRR:  82.39
FR1:  114.97
FR2:  147.62
FR3:  174.26


In [8]:
Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac

F = np.cos(np.pi/6)*1.88*2 # min distance between cool channels
print(F)

print('R1:')
n = int(np.floor((FR1-IRR)/F))
print(n)
p = (FR1-IRR)/n
R1 = [IRR]
for i in range(n-1):
    R1.append(R1[-1]+p)
print(np.round(R1, 2))
R1 = np.array(R1)
Rt = sum(R1)
t = (-2*Rt + np.sqrt(4*Rt**2+4*n*AcR1/np.pi))/2/n
print(t)
R1o = R1 + t
# print(np.round(Ro, 2))
# print(sum(np.pi*(Ro**2-R**2)))

print('R2:')
n = int(np.floor((FR2-FR1)/F))
print(n)
p = (FR2-FR1)/n
# print(p)
R2 = [FR1]
for i in range(n-1):
    R2.append(R2[-1]+p)
print(np.round(R2, 2))
R2 = np.array(R2)
Rt = sum(R2)
t = (-2*Rt + np.sqrt(4*Rt**2+4*n*AcR2/np.pi))/2/n
print(t)
R2o = R2 + t
# print(np.round(Ro, 2))
# print(sum(np.pi*(Ro**2-R**2)))

print('R3:')
n = int(np.floor((FR3-FR2)/F))
print(n)
p = (FR3-FR2)/n
# print(p)
R3 = [FR2]
for i in range(n-1):
    R3.append(R3[-1]+p)
print(np.round(R3, 2))
R3 = np.array(R3)
Rt = sum(R3)
t = (-2*Rt + np.sqrt(4*Rt**2+4*n*AcR3/np.pi))/2/n
print(t)
R3o = R3 + t
# print(np.round(Ro, 2))
# print(sum(np.pi*(Ro**2-R**2)))


3.2562555182294894
R1:
10
[ 82.39  85.65  88.91  92.16  95.42  98.68 101.94 105.2  108.46 111.71]
0.7213107524064298
R2:
10
[114.97 118.24 121.5  124.77 128.03 131.3  134.56 137.83 141.09 144.36]
0.7205173183213901
R3:
8
[147.62 150.95 154.28 157.61 160.94 164.27 167.6  170.93]
0.7335494845636958


In [9]:
# power density averaged in the ring (divided into layers)
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6
AFR1 = 18*AF
AFR2 = 24*AF
AFR3 = 24*AF

Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac


file = pd.read_csv('power.csv')

# W/cm3
R1Fs = np.zeros(10)
for i in range(1, 7):
    fi = np.array(file['F'+str(i)].tolist())
    R1Fs += fi/6/1e6

R2Fs = np.zeros(10)
for i in range(7, 15):
    fi = np.array(file['F'+str(i)].tolist())
    R2Fs += fi/8/1e6

R3Fs = np.zeros(10)
for i in range(15, 23):
    fi = np.array(file['F'+str(i)].tolist())
    R3Fs += fi/8/1e6

QR1s = R1Fs*AFR1/(AFR1-AcR1)
QR2s = R2Fs*AFR2/(AFR2-AcR2)
QR3s = R3Fs*AFR3/(AFR3-AcR3)
print('Ring one power density: ', QR1s)
print('Ring two power density: ', QR2s)
print('Ring three power density: ', QR3s)

Ring one power density:  [ 4.9573133   5.68414705  6.43529391  7.22205732  8.24619338  9.83422275
 11.11919146 12.03093274 11.61355785  8.95553876]
Ring two power density:  [3.88017895 4.55342791 5.33080732 5.97094567 6.74256671 8.11513723
 9.00992332 9.59055856 8.97985186 6.61380325]
Ring three power density:  [ 4.21320445  4.99842164  5.82826616  6.5459825   7.44364777  9.06654726
 10.14528115 10.83100657 10.10481264  7.13125642]


In [10]:
# simple - film
rho = 5.7030  # [kg/m3] 6.4 MPa 259 C
cp = 5.188  # [J/g/K] 6.4 MPa 259 C [2]
cp *= 1e3  # [J/kg/K]
mu = 2.9744e-5  # Pa.s 6.4 MPa 259 C
v = 1701.71  # cm/s
v /= 100  # m/s

Ri = np.concatenate([R1, R2, R3])
Ro = np.concatenate([R1o, R2o, R3o])

ri = Ri/100 # m
ro = Ro/100
Ah = np.pi*(ro**2-ri**2)
Ph = 2*np.pi*(ri+ro)
Dh = 4*Ah/Ph
Re = rho * v * Dh / mu
# print('Re: ', Re)

k = 0.41 # W/m/K
Pr = mu * cp/k
# print('Pr: ', Pr)

Nu = 0.023*(Re**0.8)*(Pr**0.4)
# print('Nu: ', Nu)
h = Nu/Dh * k  # W/m^2/K
# print('h: ', h)

h /= 1e4  # W/cm^2/K

ri *= 100  # cm
ro *= 100  # cm
dr = 0.01  # cm

kgci = h * (ri + dr) * np.log(1 + dr/ri)
kgco = h * (ro + dr) * np.log(1 + dr/ro)
print('ki: ', np.average(kgci))  # W/cm/C
print('ko: ', np.average(kgco))  # W/cm/C

ki:  0.002417876793408105
ko:  0.0024178761686396532
