In [1]:
import numpy as np
import pandas as pd

def calc_Rs(R1, R2, A):
    midR = (R1+R2)/2
    Ro = (A/np.pi+4*midR**2)/4/midR
    Ri = 2*midR - Ro
    return Ri, midR, Ro

# First Model

## Geometric definition

In [9]:
# Rings radius
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6

AIRR1 = AF
AIRR2 = 6*AF
AIRR3 = 12*AF
AFR1 = 18*AF
AFR2 = 24*AF
AFR3 = 24*AF
AORR1 = 36*AF
AORR2 = 42*AF

R = []

Ai = AIRR1
IRR1 = np.sqrt(1/np.pi*Ai)
R.append(IRR1)
print('IRR1: ', np.round(IRR1, 2))

Ai += AIRR2
IRR2 = np.sqrt(1/np.pi*Ai)
R.append(IRR2)
print('IRR2: ', np.round(IRR2, 2))

Ai += AIRR3
IRR3 = np.sqrt(1/np.pi*Ai)
R.append(IRR3)
print('IRR3: ', np.round(IRR3, 2))

Ai += AFR1
FR1 = np.sqrt(1/np.pi*Ai)
R.append(FR1)
print('FR1: ', np.round(FR1, 2))

Ai += AFR2
FR2 = np.sqrt(1/np.pi*Ai)
R.append(FR2)
print('FR2: ', np.round(FR2, 2))

Ai += AFR3
FR3 = np.sqrt(1/np.pi*Ai)
R.append(FR3)
print('FR3: ', np.round(FR3, 2))

Ai += AORR1
ORR1 = np.sqrt(1/np.pi*Ai)
R.append(ORR1)
print('ORR1: ', np.round(ORR1, 2))

Ai += AORR2
ORR2 = np.sqrt(1/np.pi*Ai)
R.append(ORR2)
print('ORR2: ', np.round(ORR2, 2))

ORR3 = 297.3
R.append(ORR3)

R = np.array(R)

IRR1:  18.9
IRR2:  50.01
IRR3:  82.39
FR1:  114.97
FR2:  147.62
FR3:  174.26
ORR1:  207.91
ORR2:  241.32


In [10]:
# Coolant channel radii
Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac
Actotal = AcR1 + AcR2 + AcR3

RT = sum(R)

t = (2*RT - np.sqrt(4*RT**2 - 36*Actotal/np.pi))/18
# print(t)
Rji = R - t
print(Rji)

[ 16.95831145  48.06523701  80.4460442  113.02939742 145.68124081
 172.31881817 205.97183589 239.37327269 295.356959  ]


In [11]:
# power density averaged in the ring (divided into layers)
file = pd.read_csv('power.csv')

# W/cm3
R1Fs = np.zeros(10)
for i in range(1, 7):
    fi = np.array(file['F'+str(i)].tolist())
    R1Fs += fi/6/1e6

R2Fs = np.zeros(10)
for i in range(7, 15):
    fi = np.array(file['F'+str(i)].tolist())
    R2Fs += fi/8/1e6

R3Fs = np.zeros(10)
for i in range(15, 23):
    fi = np.array(file['F'+str(i)].tolist())
    R3Fs += fi/8/1e6

QR1s = R1Fs*AFR1/(AFR1-np.pi*(FR1**2-R[3]**2))
QR2s = R2Fs*AFR2/(AFR2-np.pi*(FR2**2-R[4]**2))
QR3s = R3Fs*AFR3/(AFR3-np.pi*(FR3**2-R[5]**2))
print('Ring one power density: ', QR1s)
print('Ring two power density: ', QR2s)
print('Ring three power density: ', QR3s)

Ring one power density:  [3.874      4.442      5.029      5.64383333 6.44416667 7.68516667
 8.68933333 9.40183333 9.07566667 6.9985    ]
Ring two power density:  [3.03225  3.558375 4.165875 4.666125 5.269125 6.34175  7.041    7.49475
 7.0175   5.1685  ]
Ring three power density:  [3.2925   3.906125 4.554625 5.1155   5.817    7.08525  7.92825  8.464125
 7.896625 5.572875]


In [12]:
# film thermal conductivity
rho = 5.7030  # [kg/m3] 6.4 MPa 259 C
cp = 5.188  # [J/g/K] 6.4 MPa 259 C [2]
cp *= 1e3  # [J/kg/K]
mu = 2.9744e-5  # Pa.s 6.4 MPa 259 C
v = 1701.71  # cm/s
v /= 100  # m/s

ri = Rji/100 # m
ro = R/100
Ah = np.pi*(ro**2-ri**2)
Ph = 2*np.pi*(ri+ro)
Dh = 4*Ah/Ph
Re = rho * v * Dh / mu
print('Re: ', Re)

k = 0.41 # W/m/K
Pr = mu * cp/k
print('Pr: ', Pr)

Nu = 0.023*(Re**0.8)*(Pr**0.4)
print('Nu: ', Nu)
h = Nu/Dh * k  # W/m^2/K
print('h: ', h)

h /= 1e4  # W/cm^2/K

ri *= 100  # cm
ro *= 100  # cm
dr = 0.01  # cm

kgci = h * (ri + dr) * np.log(1 + dr/ri)
kgco = h * (ro + dr) * np.log(1 + dr/ro)
print('ki: ', kgci)  # W/cm/C
print('ko: ', kgco)  # W/cm/C

Re:  [126794.81959681 126794.81959681 126794.81959681 126794.81959681
 126794.81959681 126794.81959681 126794.81959681 126794.81959681
 126794.81959681]
Pr:  0.37637041951219513
Nu:  [188.12877923 188.12877923 188.12877923 188.12877923 188.12877923
 188.12877923 188.12877923 188.12877923 188.12877923]
h:  [1984.84745186 1984.84745186 1984.84745186 1984.84745186 1984.84745186
 1984.84745186 1984.84745186 1984.84745186 1984.84745186]
ki:  [0.00198543 0.00198505 0.00198497 0.00198494 0.00198492 0.00198491
 0.0019849  0.00198489 0.00198488]
ko:  [0.00198537 0.00198505 0.00198497 0.00198493 0.00198491 0.0019849
 0.0019849  0.00198489 0.00198488]


# Second Model 

## Geometric definition

In [2]:
# Rings radius
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6

AIR = 19*AF
AR1 = 18*AF
AR2 = 24*AF
AR3 = 24*AF

RIR = np.sqrt(1/np.pi*AIR)
print('RIR: ', np.round(RIR, 2))
RR1 = np.sqrt(1/np.pi*(AIR+AR1))
print('RR1: ', np.round(RR1, 2))
RR2 = np.sqrt(1/np.pi*(AIR+AR1+AR2))
print('RR2: ', np.round(RR2, 2))
RR3 = np.sqrt(1/np.pi*(AIR+AR1+AR2+AR3))
print('RR3: ', np.round(RR3, 2))

RIR:  82.39
RR1:  114.97
RR2:  147.62
RR3:  174.26


In [3]:
# Coolant channel radii
Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac

# R1 coolant
R1Ri, midR1, R1Ro = calc_Rs(RIR, RR1, AcR1)
print(np.round(calc_Rs(RIR, RR1, AcR1), 2))

# R2 coolant
R2Ri, midR2, R2Ro = calc_Rs(RR1, RR2, AcR2)
print(np.round(calc_Rs(RR1, RR2, AcR2), 2))

# R3 coolant
R3Ri, midR3, R3Ro = calc_Rs(RR2, RR3, AcR3)
print(np.round(calc_Rs(RR2, RR3, AcR3), 2))

[ 95.12  98.68 102.24]
[127.73 131.3  134.87]
[158.03 160.94 163.85]


In [12]:
# RPV
t = 340.8-327.5  #cm
R = 297.3 + t
print(R)

310.6


## Power density

In [10]:
# power density averaged in the ring (divided into layers)
file = pd.read_csv('power.csv')

# W/cm3
R1Fs = np.zeros(10)
for i in range(1, 7):
    fi = np.array(file['F'+str(i)].tolist())
    R1Fs += fi/6/1e6

R2Fs = np.zeros(10)
for i in range(7, 15):
    fi = np.array(file['F'+str(i)].tolist())
    R2Fs += fi/8/1e6

R3Fs = np.zeros(10)
for i in range(15, 23):
    fi = np.array(file['F'+str(i)].tolist())
    R3Fs += fi/8/1e6

QR1s = R1Fs*AR1/(AR1-AcR1)
QR2s = R2Fs*AR2/(AR2-AcR2)
QR3s = R3Fs*AR3/(AR3-AcR3)
print('Ring one power density: ', QR1s)
print('Ring two power density: ', QR2s)
print('Ring three power density: ', QR3s)

Ring one power density:  [ 4.9573133   5.68414705  6.43529391  7.22205732  8.24619338  9.83422275
 11.11919146 12.03093274 11.61355785  8.95553876]
Ring two power density:  [3.88017895 4.55342791 5.33080732 5.97094567 6.74256671 8.11513723
 9.00992332 9.59055856 8.97985186 6.61380325]
Ring three power density:  [ 4.21320445  4.99842164  5.82826616  6.5459825   7.44364777  9.06654726
 10.14528115 10.83100657 10.10481264  7.13125642]


## Coolant properties

In [19]:
# helium velocity
m = 157.1  # kg/s
At = AcR1 + AcR2 + AcR3
rho = 5.7030e-6  # kg/cm3
v = m/rho/At
print(v)  # cm/s

1701.709941080526


In [56]:
# simple - film
rho = 5.7030  # [kg/m3] 6.4 MPa 259 C
cp = 5.188  # [J/g/K] 6.4 MPa 259 C [2]
cp *= 1e3  # [J/kg/K]
mu = 2.9744e-5  # Pa.s 6.4 MPa 259 C
v = 1701.71  # cm/s
v /= 100  # m/s

ri = R3Ri/100 # m
ro = R3Ro/100
Ah = np.pi*(ro**2-ri**2)
Ph = 2*np.pi*(ri+ro)
Dh = 4*Ah/Ph
Re = rho * v * Dh / mu
print('Re: ', Re)

k = 0.41 # W/m/K
Pr = mu * cp/k
print('Pr: ', Pr)

Nu = 0.023*(Re**0.8)*(Pr**0.4)
print('Nu: ', Nu)
h = Nu/Dh * k  # W/m^2/K
print('h: ', h)

h /= 1e4  # W/cm^2/K

ri *= 100  # cm
ro *= 100  # cm
dr = 0.01  # cm

kgci = h * (ri + dr) * np.log(1 + dr/ri)
kgco = h * (ro + dr) * np.log(1 + dr/ro)
print('ki: ', kgci)  # W/cm/C
print('ko: ', kgco)  # W/cm/C

Re:  379858.61335534276
Pr:  0.37637041951219513
Nu:  452.5552548816472
h:  1593.7604317472117
ki:  0.0015938108557548198
ko:  0.0015938090644267088


In [57]:
k1 = 0.001539
k2 = 0.001530
k3 = 0.001594

print((k1+k2+k3)/3)

0.0015543333333333331


## Unit cell model definition

In [11]:
# unitcell - R1 w/layers - power density
Af = 210*np.pi*0.6225**2
Qf1 = R1Fs*AR1/18/Af
print(Qf1)
Qf2 = R2Fs*AR1/18/Af
print(Qf2)
Qf3 = R3Fs*AR1/18/Af
print(Qf3)

[17.00776986 19.50142327 22.07849113 24.77775387 28.29140517 33.73968663
 38.14821414 41.27625648 39.84430821 30.7250587 ]
[13.31228967 15.62210198 18.28916966 20.48538465 23.13269628 27.84177195
 30.91164368 32.90371275 30.80847316 22.69092889]
[14.45484829 17.14880616 19.99587347 22.45824645 25.5379962  31.10591157
 34.80687956 37.15949667 34.66803838 24.46623012]


In [26]:
# unitcell - film
rho = 5.7030  # [kg/m3] 6.4 MPa 259 C
cp = 5.188  # [J/g/K] 6.4 MPa 259 C [2]
cp *= 1e3  # [J/kg/K]
mu = 2.9744e-5  # Pa.s 6.4 MPa 259 C
v = 1701.71  # cm/s
v /= 100  # m/s
rc = 1.588/2  # cm
D = 2 * rc / 100  # m
Re = rho * v * D / mu
print('Re: ', Re)

k = 0.41 # W/m/K
Pr = mu * cp/k
print('Pr: ', Pr)

Nu = 0.023*(Re**0.8)*(Pr**0.4)
print('Nu: ', Nu)
h = Nu/D * k  # W/m^2/K
print('h: ', h)

rc = 1.588/2  # cm
dr = 0.01  # cm

h /= 1e4  # W/cm^2/K
kgc = h * (rc + dr) * np.log(1 + dr/rc)
print('kgc: ', kgc)  # W/cm/C

Re:  51813.156207773005
Pr:  0.37637041951219513
Nu:  91.94456614236985
h:  2373.8836346581634
kgc:  0.002388770158561358
