In [2]:
import numpy as np
import pandas as pd

def calc_Rs(R1, R2, A):
    midR = (R1+R2)/2
    Ro = (A/np.pi+4*midR**2)/4/midR
    Ri = 2*midR - Ro   
    return Ri, midR, Ro

In [19]:
# Rings radius
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6

AIR = 19*AF
AR1 = 18*AF
AR2 = 24*AF
AR3 = 24*AF

RIR = np.sqrt(1/np.pi*AIR)
print('RIR: ', np.round(RIR, 2))
RR1 = np.sqrt(1/np.pi*(AIR+AR1))
print('RR1: ', np.round(RR1, 2))
RR2 = np.sqrt(1/np.pi*(AIR+AR1+AR2))
print('RR2: ', np.round(RR2, 2))
RR3 = np.sqrt(1/np.pi*(AIR+AR1+AR2+AR3))
print('RR3: ', np.round(RR3, 2))

RIR:  82.39
RR1:  114.97
RR2:  147.62
RR3:  174.26


In [53]:
# Coolant channel radii
Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac

# R1 coolant
R1Ri, midR1, R1Ro = calc_Rs(RIR, RR1, AcR1)
print(np.round(calc_Rs(RIR, RR1, AcR1), 2))

# R2 coolant
R2Ri, midR2, R2Ro = calc_Rs(RR1, RR2, AcR2)
print(np.round(calc_Rs(RR1, RR2, AcR2), 2))

# R3 coolant
R3Ri, midR3, R3Ro = calc_Rs(RR2, RR3, AcR3)
print(np.round(calc_Rs(RR2, RR3, AcR3), 2))

[ 95.12  98.68 102.24]
[127.73 131.3  134.87]
[158.03 160.94 163.85]


In [18]:
# Fuel radius
Af = 210*np.pi*0.6225**2
AfR1 = 18*Af/2
AfR2 = 24*Af/2
AfR3 = 24*Af/2

# R1
print(np.round(calc_Rs(RIR, midR1, AfR1), 2))
print(np.round(calc_Rs(midR1, RR1, AfR1), 2))

# R2
print(np.round(calc_Rs(RR1, midR2, AfR2), 2))
print(np.round(calc_Rs(midR2, RR2, AfR2), 2))

# R3
print(np.round(calc_Rs(RR2, midR3, AfR3), 2))
print(np.round(calc_Rs(midR3, RR3, AfR3), 2))

[88.51 90.53 92.56]
[105.11 106.83 108.54]
[121.15 123.14 125.12]
[137.71 139.46 141.21]
[152.7  154.28 155.87]
[166.15 167.6  169.06]


## assembly

In [3]:
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6
Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
Af = 210*np.pi*0.6225**2

R = np.sqrt(1/np.pi*AF)
print('Assembly radius: ', R)

_, midR, _ = calc_Rs(0, R, Ac)
print(np.round(calc_Rs(0, R, Ac), 2))

print(np.round(calc_Rs(0, midR, Af/2), 2))
print(np.round(calc_Rs(midR, R, Af/2), 2))


Assembly radius:  18.90135244455595
[ 7.39  9.45 11.52]
[2.57 4.73 6.88]
[13.46 14.18 14.89]


## simple

In [9]:
# power density
file = pd.read_csv('power.csv')

# W/cm3
R1Fs = []
for i in range(1, 7):
    fi = np.array(file['F'+str(i)].tolist())
    R1Fs.append(np.average(fi)/1e6)
R1F = np.average(np.array(R1Fs))

R2Fs = []
for i in range(7, 15):
    fi = np.array(file['F'+str(i)].tolist())
    R2Fs.append(np.average(fi)/1e6)
R2F = np.average(np.array(R2Fs))

R3Fs = []
for i in range(15, 23):
    fi = np.array(file['F'+str(i)].tolist())
    R3Fs.append(np.average(fi)/1e6)
R3F = np.average(np.array(R3Fs))

print('Ring one power density: ', R1F)
print('Ring two power density: ', R2F)
print('Ring three power density: ', R3F)

# Rings radius
P = 18  # cm
F = P/np.cos(np.pi/6)
AF = F/2 * P * 6

AIR = 19*AF
AR1 = 18*AF
AR2 = 24*AF
AR3 = 24*AF

# Coolant channel radii
Ac = 120*np.pi*0.794**2 + 6*np.pi*0.635**2
AcR1 = 18*Ac
AcR2 = 24*Ac
AcR3 = 24*Ac

QR1 = R1F*AR1/(AR1-AcR1)
QR2 = R2F*AR2/(AR2-AcR2)
QR3 = R3F*AR3/(AR3-AcR3)
print('Ring one adjusted power density: ', QR1)
print('Ring two adjusted power density: ', QR2)
print('Ring three adjusted power density: ', QR3)

Ring one power density:  6.72835
Ring two power density:  5.3755250000000006
Ring three power density:  5.9632875
Ring one adjusted power density:  8.609844851899053
Ring two adjusted power density:  6.878720079589299
Ring three adjusted power density:  7.630842655668771


In [10]:
# power density averaged in the ring (divided into layers)
file = pd.read_csv('power.csv')

# W/cm3
R1Fs = np.zeros(10)
for i in range(1, 7):
    fi = np.array(file['F'+str(i)].tolist())
    R1Fs += fi/6/1e6

R2Fs = np.zeros(10)
for i in range(7, 15):
    fi = np.array(file['F'+str(i)].tolist())
    R2Fs += fi/8/1e6

R3Fs = np.zeros(10)
for i in range(15, 23):
    fi = np.array(file['F'+str(i)].tolist())
    R3Fs += fi/8/1e6

QR1s = R1Fs*AR1/(AR1-AcR1)
QR2s = R2Fs*AR2/(AR2-AcR2)
QR3s = R3Fs*AR3/(AR3-AcR3)
print('Ring one power density: ', QR1s)
print('Ring two power density: ', QR2s)
print('Ring three power density: ', QR3s)

Ring one power density:  [ 4.9573133   5.68414705  6.43529391  7.22205732  8.24619338  9.83422275
 11.11919146 12.03093274 11.61355785  8.95553876]
Ring two power density:  [3.88017895 4.55342791 5.33080732 5.97094567 6.74256671 8.11513723
 9.00992332 9.59055856 8.97985186 6.61380325]
Ring three power density:  [ 4.21320445  4.99842164  5.82826616  6.5459825   7.44364777  9.06654726
 10.14528115 10.83100657 10.10481264  7.13125642]


In [19]:
# helium velocity
m = 157.1  # kg/s
At = AcR1 + AcR2 + AcR3
rho = 5.7030e-6  # kg/cm3
v = m/rho/At
print(v)  # cm/s

1701.709941080526


In [56]:
# simple - film
rho = 5.7030  # [kg/m3] 6.4 MPa 259 C
cp = 5.188  # [J/g/K] 6.4 MPa 259 C [2]
cp *= 1e3  # [J/kg/K]
mu = 2.9744e-5  # Pa.s 6.4 MPa 259 C
v = 1701.71  # cm/s
v /= 100  # m/s

ri = R3Ri/100 # m
ro = R3Ro/100
Ah = np.pi*(ro**2-ri**2)
Ph = 2*np.pi*(ri+ro)
Dh = 4*Ah/Ph
Re = rho * v * Dh / mu
print('Re: ', Re)

k = 0.41 # W/m/K
Pr = mu * cp/k
print('Pr: ', Pr)

Nu = 0.023*(Re**0.8)*(Pr**0.4)
print('Nu: ', Nu)
h = Nu/Dh * k  # W/m^2/K
print('h: ', h)

h /= 1e4  # W/cm^2/K

ri *= 100  # cm
ro *= 100  # cm
dr = 0.01  # cm

kgci = h * (ri + dr) * np.log(1 + dr/ri)
kgco = h * (ro + dr) * np.log(1 + dr/ro)
print('ki: ', kgci)  # W/cm/C
print('ko: ', kgco)  # W/cm/C

Re:  379858.61335534276
Pr:  0.37637041951219513
Nu:  452.5552548816472
h:  1593.7604317472117
ki:  0.0015938108557548198
ko:  0.0015938090644267088


In [57]:
k1 = 0.001539
k2 = 0.001530
k3 = 0.001594

print((k1+k2+k3)/3)

0.0015543333333333331


In [51]:
# RPV
t = 340.8-327.5  #cm
R = 297.3 + t
print(R)

k = 40.0 # W/m/K

310.6


In [49]:
# simple - outer film bc

g = 9.8  # m/s^2
Tinf = 30  # C: room temperature
Tsl = np.array([50, 100, 150, 200, 250, 300, 350, 400, 450, 500])  # Twall
L = 200+793+120  # cm
L /= 100 # m

# data from table A-9 cengel, 1 atm pressure
templ = np.array([50, 100, 150, 200, 250, 300, 350, 400, 450, 500])  # C
nul = np.array([1.798e-5, 2.306e-5, 2.745e-5, 3.455e-5, 4.091e-5, 4.765e-5, 5.475e-5, 6.219e-5, 6.997e-5, 7.806e-5])  # m^2/s
Prl = np.array([0.7228, 0.7111, 0.7041, 0.6974, 0.6946, 0.6935, 0.6937, 0.6948, 0.6965, 0.6986])
Tf = 0.5*(Tsl+Tinf)

nu = np.interp(Tf, templ, nul)
beta = 1/(Tf+273)  # ideal gas assumption

# formula 9-16 from Cengel - Heat transfer
Gr = g*beta*(Tsl-Tinf)*L**3/nu**2
# D = 297.3*2  # cm
# L *= 100 # cm
# Dt = 35*L/Gr**0.25
# print(Dt) # is D > Dt? Dt < D
# can't use the vertical plat approximation
# need to go to Cebeci 1974

Pr = np.interp(Tf, templ, Prl)
Ra = Gr * Pr
print(Ra)

# same correlation for isothermal and constant heat flux
# from Laminar Natural Convection From Isothermal Vertical Cylinders: Revistinga Classical Subject
D = 297.3*2/100  # m

Nufp = 0.68 + 0.67*Ra**0.25/(1+(0.492/Pr)**(9/16))**(4/9)
# print(Nufp)
Nu = (1 + 0.3*(32**0.5/Gr**0.25*L/D)**0.909)*Nufp
print(Nu)

kl = [0.02735, 0.03095, 0.03374, 0.03779, 0.04104, 0.04418, 0.04721, 0.05015, 0.05298, 0.05572]  # W/m/K
k = np.interp(Tf, templ, kl)
h = Nu*k/D
print(h)  # W/m2/K
print(np.average(h))  # W/m2/K

[1.93034972e+12 5.29114367e+12 6.55787056e+12 7.06341112e+12
 7.19171931e+12 6.68340332e+12 5.94501959e+12 5.36866520e+12
 4.89446021e+12 4.44624417e+12]
[610.37829168 784.13588871 826.44379254 841.28510071 844.59523238
 828.85613482 804.59468672 784.1354499  766.10482122 747.88706177]
[2.8075759  3.74924038 4.20171474 4.49746544 4.71331298 4.87263138
 5.00402145 5.11217806 5.20399827 5.28049018]
4.544262877865347


In [52]:
# unitcell - R1 - power density
Af = 210*np.pi*0.6225**2
Qf = R1F*AR1/18/Af
print(Qf)

29.539036746538077


In [11]:
# unitcell - R1 w/layers - power density
Af = 210*np.pi*0.6225**2
Qf1 = R1Fs*AR1/18/Af
print(Qf1)
Qf2 = R2Fs*AR1/18/Af
print(Qf2)
Qf3 = R3Fs*AR1/18/Af
print(Qf3)

[17.00776986 19.50142327 22.07849113 24.77775387 28.29140517 33.73968663
 38.14821414 41.27625648 39.84430821 30.7250587 ]
[13.31228967 15.62210198 18.28916966 20.48538465 23.13269628 27.84177195
 30.91164368 32.90371275 30.80847316 22.69092889]
[14.45484829 17.14880616 19.99587347 22.45824645 25.5379962  31.10591157
 34.80687956 37.15949667 34.66803838 24.46623012]


In [26]:
# unitcell - film
rho = 5.7030  # [kg/m3] 6.4 MPa 259 C
cp = 5.188  # [J/g/K] 6.4 MPa 259 C [2]
cp *= 1e3  # [J/kg/K]
mu = 2.9744e-5  # Pa.s 6.4 MPa 259 C
v = 1701.71  # cm/s
v /= 100  # m/s
rc = 1.588/2  # cm
D = 2 * rc / 100  # m
Re = rho * v * D / mu
print('Re: ', Re)

k = 0.41 # W/m/K
Pr = mu * cp/k
print('Pr: ', Pr)

Nu = 0.023*(Re**0.8)*(Pr**0.4)
print('Nu: ', Nu)
h = Nu/D * k  # W/m^2/K
print('h: ', h)

rc = 1.588/2  # cm
dr = 0.01  # cm

h /= 1e4  # W/cm^2/K
kgc = h * (rc + dr) * np.log(1 + dr/rc)
print('kgc: ', kgc)  # W/cm/C

Re:  51813.156207773005
Pr:  0.37637041951219513
Nu:  91.94456614236985
h:  2373.8836346581634
kgc:  0.002388770158561358
